### ISSUE TITLE
Stemming single-item array should yield an array

### ISSUE THREAD

**Issue by mahemoff** [aurelian/ruby-stemmer#22]
Hi, I think this behaviour is inconsistent:

> Lingua.stemmer(["installation"])
"instal" # string
> Lingua.stemmer(["installation", "installation"])
["instal", "instal"] # not a string!

It makes it hard to treat arbitrary strings as some post-processing is necessary to neutralise the return data type. I would suggest the first example should yield ["instal"].

**Comment by aurelian** [comment]
Yeah, I guess it makes sense.
