### ISSUE TITLE
"simply" and "simple" give different stems

### ISSUE THREAD

**Issue by jackdesert** [aurelian/ruby-stemmer#25]
I expected "simply" and "simple" to have the same stem, but they do not:

    > s = Lingua::Stemmer.new
    > s.stem('simply')
    => "simpli"
    > s.stem('simple')
    => "simpl"

**Comment by aurelian** [comment]
That's correct, is how the Snowball Stemmer works.
This nltk demo is producing same results: http://text-processing.com/demo/stem/
